CURRENT_DIR = $(shell echo `pwd`)
SOURCE_DIR = $(shell echo `pwd`)
TARGET_DIR = $(shell echo `pwd`)

PROJECT_NAME = list

.PHONY: all

all:	
	g++ -Wall -W -g -o $(TARGET_DIR)/$(PROJECT_NAME) $(SOURCE_DIR)/$(PROJECT_NAME).cpp

